const routePaths = {
  webHome: "/",
  dashboard: {
    base: "/dashboard",
    home: "/dashboard/home",
    post: '/dashboard/posts',
    editPost: '/dashboard/posts/edit_posts/:postId',
    addPost: '/dashboard/posts/add_post',
    comment: '/dashboard/comments',
    singleComment: '/dashboard/comments/:commentId',
    tours: "/dashboard/tours",
    singleTours: "/dashboard/tours/:tourId",
    addTour: "/dashboard/tours/add_tour",
    editTour: "/dashboard/tours/edit_tour/:tourId",
    tourReviews: "/dashboard/tours/reviews",
    users: "/dashboard/users",
    gallery: "/dashboard/gallery",
    addUser: "/dashboard/users/add_user",
    sellerApplications: "/dashboard/users/seller-applications",
    editUser: "/dashboard/users/:userId",
    tourSetting: "/dashboard/tours/tour_setting",
    tourCategory: "/dashboard/tours/tour_category",
    tourFacts: "/dashboard/tours/tour_facts",
    tourFaq: "/dashboard/tours/tour_faq",
    tourDestination: "/dashboard/tours/tour_destination",
    subscribers: "/dashboard/subscribers",
    setting: "/dashboard/setting",
  },
  home: {
    base: "/",
    home: "/",
    tours: "/tours",
    singleTours: "/tours/:tourId",
    blog: "/blog",
    singleBlog: "/blog/:id",
    about: "/about",
    contact: "/contact",
    applySeller: "/apply-seller",
  },
  auth: {
    base: "/auth",
    login: "/auth/login",
    verify: "/auth/login/verify",
    forgot: "/auth/login/forgot",
    register: "/auth/register",
  },
  error: "*",
};

export default routePaths;